version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_melivecode
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
    - C:\Users\Mac\mysql-docker:/var/lib/mysql # แมปไดเรกทอรีของเครื่องโฮสต์ไปยังไดเรกทอรีภายใน container
    ports:
    - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-server
    restart: always
    environment:
    # ในสภาพการทำงานจริง การตั้งค่า PMA_ARBITRARY: 1 ควรถูกใช้อย่างระมัดระวัง เพราะมันอนุญาตให้ PHPMyAdmin เชื่อมต่อกับเซิร์ฟเวอร์ MySQL ใดๆ ก็ตาม โดยไม่จำเป็นต้องระบุล่วงหน้า (เป็นการเชื่อมต่อแบบไม่จำกัด hostnames)
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
    - mysql